[env]
EDITOR = "hx"
VISUAL = "hx"

[tools]
aube = "latest"
bat = "latest"
bottom = "latest"
elixir = "latest"
erlang = "latest"
"github:elixir-lang/expert" = "latest"
flyctl = "latest"
"forgejo:forgejo-contrib/forgejo-cli" = "latest"
fzf = "latest"
github-cli = "latest"
go = "latest"
jj = "latest"
lazygit = "latest"
"github:joelpaulkoch/mdy" = "latest"
node = "latest"
opencode = "latest"
pitchfork = "latest"
python = "latest"
resvg = "latest"
rust = "latest"
tokei = "latest"
websocat = "latest"
yazi = "latest"
zig = "latest"
zls = "latest"

[settings]
experimental = true

