[language-server.expert]
command = "expert"
args = ["--stdio"]

[language-server.ruby-lsp]
auto-signature-help = false

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true

[[language]]
name = "elixir"
language-servers = ["expert"]
auto-format = true

[[language]]
name = "heex"
language-servers = ["expert"]

[[language]]
name = "ruby"
auto-format = true
language-servers = ["ruby-lsp"]
file-types = ["rb", "haml"]

[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "json"
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "css"
auto-format = true
language-servers = ["deno-lsp"]
