[language-server.expert]
command = "expert"
args = ["--stdio"]

[language-server.ruby-lsp]
auto-signature-help = false

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[language-server.biome.config.biome.inlineConfig]
formatter.indentStyle = "spaces"

[[language]]
name = "elixir"
language-servers = ["expert"]
auto-format = true

[[language]]
name = "heex"
language-servers = ["expert"]

[[language]]
name = "ruby"
auto-format = true
language-servers = ["ruby-lsp"]
file-types = ["rb", "haml"]

[[language]]
name = "typescript"
roots = ["biome.json", "biome.jsonc", "package.json"]
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "javascript"
roots = ["biome.json", "biome.jsonc", "package.json"]
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "astro"
roots = ["biome.json", "biome.jsonc", "package.json"]
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "json"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "css"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true
