[env]
EDITOR = "hx"
VISUAL = "hx"

[plugins]
helix = "https://github.com/CSergienko/asdf-helix"

[tools]
bat = "latest"
bottom = "latest"
elixir = "latest"
erlang = "latest"
flyctl = "latest"
fzf = "latest"
github-cli = "latest"
helix = "latest"
lazygit = "latest"
python = "latest"
tokei = "latest"
zig = "latest"

